- name: Deploy webserver role on EC2 instances
  hosts: role_web
  gather_facts: no
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: /home/vagrant/PSS-Talent/Practica_Final/Dev-Workspace/terraform-dev/ssh_key_nachodele.pem

  roles:
    - webserver

- name: Deploy database role on DB instances
  hosts: role_db
  gather_facts: no
  remote_user: ubuntu

  roles:
    - database

